Added helm chart version update workflow

diff --git a/.github/workflows/node-ci-build.yml b/.github/workflows/node-ci-build.yml
--- a/.github/workflows/node-ci-build.yml
+++ b/.github/workflows/node-ci-build.yml
@@ -69,6 +69,28 @@ jobs:
           file: ./Dockerfile
           push: true
           tags: ghcr.io/${{ env.IMAGE_NAME }}
+  release-helm:
+    name: 'Release Helm Chart'
+    runs-on: ubuntu-latest
+    needs: [release, release-docker]
+    steps:
+      - name: Branch Mapping
+        id: environment
+        run: |
+          if [ "${{ github.ref }}" = "refs/heads/develop" ]; then
+            echo "environment=devnet" >> "$GITHUB_OUTPUT"
+          elif [ "${{ github.ref }}" = "refs/heads/main" ]; then
+            echo "environment=main" >> "$GITHUB_OUTPUT"
+          else
+            echo "::error::Unsupported branch"
+            exit 1
+          fi
+
+      - name: Deploy Release
+        uses: ixofoundation/ixo-github-actions/.github/workflows/node-ci-deploy.yml@main
+        with:
+          environment: ${{ steps.environment.outputs.environment }}
+          version: ${{ needs.release.outputs.NEW_TAG }}
 # Notes for Deployment
 # TestNet will be deployed using the latest release image ^
 # Main will require deployment review and if approved use the latest release image ^
